[[GLPK]]
arch = "aarch64"
git-tree-sha1 = "26e82faea1a22aa31d77ea2505337117be6c3beb"
libc = "glibc"
os = "linux"

    [[GLPK.download]]
    sha256 = "c853382953bb7fd40f614b38d8f8b182ca51178ce6e8cff382dc566a05b8bd8a"
    url = "https://github.com/JuliaBinaryWrappers/GLPK_jll.jl/releases/download/GLPK-v4.65.0+1/GLPK.v4.65.0.aarch64-linux-gnu.tar.gz"
[[GLPK]]
arch = "aarch64"
git-tree-sha1 = "d59de1c5cea2c361acbf80cffb61644b8a0353b2"
libc = "musl"
os = "linux"

    [[GLPK.download]]
    sha256 = "a99a968197da38f73749a40a64966d30ea6b9c66ff36a19a5485af9fc8d8bae0"
    url = "https://github.com/JuliaBinaryWrappers/GLPK_jll.jl/releases/download/GLPK-v4.65.0+1/GLPK.v4.65.0.aarch64-linux-musl.tar.gz"
[[GLPK]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5a053cf3de3df0d11783a309956d6b8650e86ea5"
libc = "glibc"
os = "linux"

    [[GLPK.download]]
    sha256 = "c7dd004af9b7b26cc79c60cec58ae9b3d706ac76b96eae3baa7ce30b2e595d40"
    url = "https://github.com/JuliaBinaryWrappers/GLPK_jll.jl/releases/download/GLPK-v4.65.0+1/GLPK.v4.65.0.armv7l-linux-gnueabihf.tar.gz"
[[GLPK]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "99daccd3c7bf6ea93e37e7d1024c2a4a65f41bf4"
libc = "musl"
os = "linux"

    [[GLPK.download]]
    sha256 = "03ed90f582802328343e9735ea44cfbb168822746eafe8bff85c9a068c1566c7"
    url = "https://github.com/JuliaBinaryWrappers/GLPK_jll.jl/releases/download/GLPK-v4.65.0+1/GLPK.v4.65.0.armv7l-linux-musleabihf.tar.gz"
[[GLPK]]
arch = "i686"
git-tree-sha1 = "f8f0608a8d4185d614eee6fa387f1b52de614547"
libc = "glibc"
os = "linux"

    [[GLPK.download]]
    sha256 = "bd3b580c7e487ea2a5dd3ac1cd5d54f2527bebfb9ea1dac7cd85792c8d6394b7"
    url = "https://github.com/JuliaBinaryWrappers/GLPK_jll.jl/releases/download/GLPK-v4.65.0+1/GLPK.v4.65.0.i686-linux-gnu.tar.gz"
[[GLPK]]
arch = "i686"
git-tree-sha1 = "f4e98aafde51828394145343c0944d7a55fd9bf1"
libc = "musl"
os = "linux"

    [[GLPK.download]]
    sha256 = "95830b03bb067d9481803b15fd8f4134d2e451ab52b68dd9b1c25d6d8eae70cb"
    url = "https://github.com/JuliaBinaryWrappers/GLPK_jll.jl/releases/download/GLPK-v4.65.0+1/GLPK.v4.65.0.i686-linux-musl.tar.gz"
[[GLPK]]
arch = "i686"
git-tree-sha1 = "7f5aa16737e795f4befb4772f03557b3429830d4"
os = "windows"

    [[GLPK.download]]
    sha256 = "48e483343bc0bf24247bbf585bcaf41b1f7176bd7c63043b10a0dcb09c396613"
    url = "https://github.com/JuliaBinaryWrappers/GLPK_jll.jl/releases/download/GLPK-v4.65.0+1/GLPK.v4.65.0.i686-w64-mingw32.tar.gz"
[[GLPK]]
arch = "powerpc64le"
git-tree-sha1 = "c3ebc2519a1c36f18a9a0184b1076c5abc0a6024"
libc = "glibc"
os = "linux"

    [[GLPK.download]]
    sha256 = "3bb14c556c7201898d5685ddc05261048dd2a1b8b3df0f6db0f1a1dcaa835fc9"
    url = "https://github.com/JuliaBinaryWrappers/GLPK_jll.jl/releases/download/GLPK-v4.65.0+1/GLPK.v4.65.0.powerpc64le-linux-gnu.tar.gz"
[[GLPK]]
arch = "x86_64"
git-tree-sha1 = "535208ff71e2267b1d91c104eb83a91e9dfad70f"
os = "macos"

    [[GLPK.download]]
    sha256 = "e09176ed3279cf8abae5fd20107cfafb930b1d84400fa8088024b753fa2ca291"
    url = "https://github.com/JuliaBinaryWrappers/GLPK_jll.jl/releases/download/GLPK-v4.65.0+1/GLPK.v4.65.0.x86_64-apple-darwin.tar.gz"
[[GLPK]]
arch = "x86_64"
git-tree-sha1 = "660e56c5b7f2bb5e76387ec979c646b018622460"
libc = "glibc"
os = "linux"

    [[GLPK.download]]
    sha256 = "5ad37b7639eb829c4e9cd13ca038ebd743504e1a6feeb0355048b933b1e8535f"
    url = "https://github.com/JuliaBinaryWrappers/GLPK_jll.jl/releases/download/GLPK-v4.65.0+1/GLPK.v4.65.0.x86_64-linux-gnu.tar.gz"
[[GLPK]]
arch = "x86_64"
git-tree-sha1 = "0d95a8dee496b1e3cb6a059d8fa5f913778fcfaa"
libc = "musl"
os = "linux"

    [[GLPK.download]]
    sha256 = "6e3219a46a6159e7c87b2e720b9bd9b963e685d5231699d9b10b71ce149c7d97"
    url = "https://github.com/JuliaBinaryWrappers/GLPK_jll.jl/releases/download/GLPK-v4.65.0+1/GLPK.v4.65.0.x86_64-linux-musl.tar.gz"
[[GLPK]]
arch = "x86_64"
git-tree-sha1 = "69d0f48a7c756441740a658cb37c5ecb3a5265cf"
os = "freebsd"

    [[GLPK.download]]
    sha256 = "1a8faad125b9b3af4b43a1fa9c3ceb993541d1522fbd906e19a1a41cfa316a5e"
    url = "https://github.com/JuliaBinaryWrappers/GLPK_jll.jl/releases/download/GLPK-v4.65.0+1/GLPK.v4.65.0.x86_64-unknown-freebsd.tar.gz"
[[GLPK]]
arch = "x86_64"
git-tree-sha1 = "cba1f20206482d712b7cedba7b137381b2ccfaa3"
os = "windows"

    [[GLPK.download]]
    sha256 = "79c4c3de1de5a59563bb2f2b12c62074a15e57fcb08e2a64f7b2f8e386037b9a"
    url = "https://github.com/JuliaBinaryWrappers/GLPK_jll.jl/releases/download/GLPK-v4.65.0+1/GLPK.v4.65.0.x86_64-w64-mingw32.tar.gz"
