[[GLPK]]
arch = "aarch64"
git-tree-sha1 = "40fad77293103e2dd6c96d6d3242bb4033385129"
os = "macos"

    [[GLPK.download]]
    sha256 = "bd51e00a6f5cc1ca4bcc458aed92113a0f1981a4428d81d76ef045385b8f86e2"
    url = "https://github.com/JuliaBinaryWrappers/GLPK_jll.jl/releases/download/GLPK-v5.0.1+1/GLPK.v5.0.1.aarch64-apple-darwin.tar.gz"
[[GLPK]]
arch = "aarch64"
git-tree-sha1 = "bb7fcb77152c37c7205c4381d3b9b5e7e41eb467"
libc = "glibc"
os = "linux"

    [[GLPK.download]]
    sha256 = "1350422892a491a920b7550b5ed01aae6e25c13379143da46de4cc5981e07e6c"
    url = "https://github.com/JuliaBinaryWrappers/GLPK_jll.jl/releases/download/GLPK-v5.0.1+1/GLPK.v5.0.1.aarch64-linux-gnu.tar.gz"
[[GLPK]]
arch = "aarch64"
git-tree-sha1 = "21b17ddc4a26012a3a687116ddcc9a2c55377398"
libc = "musl"
os = "linux"

    [[GLPK.download]]
    sha256 = "bdfb7bd1456f76a87b2e4e0daf809995400b604354364ecf8742bde2811ed98a"
    url = "https://github.com/JuliaBinaryWrappers/GLPK_jll.jl/releases/download/GLPK-v5.0.1+1/GLPK.v5.0.1.aarch64-linux-musl.tar.gz"
[[GLPK]]
arch = "aarch64"
git-tree-sha1 = "6abcb997dd8ef9bdfcab2f208197a9077ae068d2"
os = "freebsd"

    [[GLPK.download]]
    sha256 = "cdd4135906d5cf27ad78296b197a6e5ce9828105d3f51990b2983da0d602255e"
    url = "https://github.com/JuliaBinaryWrappers/GLPK_jll.jl/releases/download/GLPK-v5.0.1+1/GLPK.v5.0.1.aarch64-unknown-freebsd.tar.gz"
[[GLPK]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0d5d4d3582b3dbe2df91ee6605c0531b0b9718e0"
libc = "glibc"
os = "linux"

    [[GLPK.download]]
    sha256 = "3ccd9ea5c6bd42d11b9297b6136ef6b6a73796955afcd718473d88fb3e22bbd9"
    url = "https://github.com/JuliaBinaryWrappers/GLPK_jll.jl/releases/download/GLPK-v5.0.1+1/GLPK.v5.0.1.armv6l-linux-gnueabihf.tar.gz"
[[GLPK]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "06adb2f19900228cb75d1e98374388e4a6092924"
libc = "musl"
os = "linux"

    [[GLPK.download]]
    sha256 = "a0c3d7d91e1b5396c2aeccc98d997ec33396a063f758c6bea7b3a4face141d93"
    url = "https://github.com/JuliaBinaryWrappers/GLPK_jll.jl/releases/download/GLPK-v5.0.1+1/GLPK.v5.0.1.armv6l-linux-musleabihf.tar.gz"
[[GLPK]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b2ae5df83bd9fdf72f9cdad8de4d23ffbc3607c2"
libc = "glibc"
os = "linux"

    [[GLPK.download]]
    sha256 = "60ad2ce951b9ab2ba1f99efdd7804769e349bf653a3f51174c877779b7bd79ce"
    url = "https://github.com/JuliaBinaryWrappers/GLPK_jll.jl/releases/download/GLPK-v5.0.1+1/GLPK.v5.0.1.armv7l-linux-gnueabihf.tar.gz"
[[GLPK]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e0308d4500093b1e3fb4f75a385a7e2d96b62e0f"
libc = "musl"
os = "linux"

    [[GLPK.download]]
    sha256 = "ee2560137eea8c94df882d1226bfb1e85c248600e86707d8f28a92ca6c4e0b34"
    url = "https://github.com/JuliaBinaryWrappers/GLPK_jll.jl/releases/download/GLPK-v5.0.1+1/GLPK.v5.0.1.armv7l-linux-musleabihf.tar.gz"
[[GLPK]]
arch = "i686"
git-tree-sha1 = "80d380b6881481153eeb843747e54880975678f5"
libc = "glibc"
os = "linux"

    [[GLPK.download]]
    sha256 = "0d06deb1a6f5fc795e8a1983d810012b4eb4908022a9c036c1a5820e10f5a198"
    url = "https://github.com/JuliaBinaryWrappers/GLPK_jll.jl/releases/download/GLPK-v5.0.1+1/GLPK.v5.0.1.i686-linux-gnu.tar.gz"
[[GLPK]]
arch = "i686"
git-tree-sha1 = "41e21a8abfa45af8b80f59b1ac4a4b4c7900759e"
libc = "musl"
os = "linux"

    [[GLPK.download]]
    sha256 = "8fbb1e99812e38e90a614384e84249820ef63758b0d264e9be1739d3a3a87432"
    url = "https://github.com/JuliaBinaryWrappers/GLPK_jll.jl/releases/download/GLPK-v5.0.1+1/GLPK.v5.0.1.i686-linux-musl.tar.gz"
[[GLPK]]
arch = "i686"
git-tree-sha1 = "d85bba3c3858a7079b4e86799454103328d0a5ce"
os = "windows"

    [[GLPK.download]]
    sha256 = "bc35aab830d61a30fa14c54b11b7b1dec9f3d57cd8f23657bdb4e8e3cd6a38ed"
    url = "https://github.com/JuliaBinaryWrappers/GLPK_jll.jl/releases/download/GLPK-v5.0.1+1/GLPK.v5.0.1.i686-w64-mingw32.tar.gz"
[[GLPK]]
arch = "powerpc64le"
git-tree-sha1 = "3b1166648a6ef6f87cf7b09799468831bb217355"
libc = "glibc"
os = "linux"

    [[GLPK.download]]
    sha256 = "f0f587b638565c7b49e7e673c2a57451420070f399dcd9ea5eb14f5204394733"
    url = "https://github.com/JuliaBinaryWrappers/GLPK_jll.jl/releases/download/GLPK-v5.0.1+1/GLPK.v5.0.1.powerpc64le-linux-gnu.tar.gz"
[[GLPK]]
arch = "x86_64"
git-tree-sha1 = "29331dab863e461fc6fc5562b6b43aac064de66e"
os = "macos"

    [[GLPK.download]]
    sha256 = "d7f2178f22079ce8e3177bc88f107ae45ee445efcba3976089d3cfac518364ea"
    url = "https://github.com/JuliaBinaryWrappers/GLPK_jll.jl/releases/download/GLPK-v5.0.1+1/GLPK.v5.0.1.x86_64-apple-darwin.tar.gz"
[[GLPK]]
arch = "x86_64"
git-tree-sha1 = "bc64c29f1b72c24f25fad29b5e5fbe3e0d8bf7b0"
libc = "glibc"
os = "linux"

    [[GLPK.download]]
    sha256 = "224f48adceabbc80d513ed9758e22490e1216b15d5d4e864a1c2d67fc133f562"
    url = "https://github.com/JuliaBinaryWrappers/GLPK_jll.jl/releases/download/GLPK-v5.0.1+1/GLPK.v5.0.1.x86_64-linux-gnu.tar.gz"
[[GLPK]]
arch = "x86_64"
git-tree-sha1 = "63470bde61999f43b08fad3ee8c6fdfdb4f4c3f4"
libc = "musl"
os = "linux"

    [[GLPK.download]]
    sha256 = "2dedfa00b78cf9b7fc8fee5b7f90d59f1ccc571666d632681218e6a42e0be5d6"
    url = "https://github.com/JuliaBinaryWrappers/GLPK_jll.jl/releases/download/GLPK-v5.0.1+1/GLPK.v5.0.1.x86_64-linux-musl.tar.gz"
[[GLPK]]
arch = "x86_64"
git-tree-sha1 = "0261b4d30b59e9ee76ae092c89e4755fc492a8ba"
os = "freebsd"

    [[GLPK.download]]
    sha256 = "82dafff83b9ec33249631f0d76c1b260c8a9bbdd0f629307272fd67fa92c6b58"
    url = "https://github.com/JuliaBinaryWrappers/GLPK_jll.jl/releases/download/GLPK-v5.0.1+1/GLPK.v5.0.1.x86_64-unknown-freebsd.tar.gz"
[[GLPK]]
arch = "x86_64"
git-tree-sha1 = "fb72705cba7e6e8826a3af9760a39316c9b035c6"
os = "windows"

    [[GLPK.download]]
    sha256 = "c9949bb439f0c061927bfd434e1adb555f9bfc115fd58560cc1e9a8541c39276"
    url = "https://github.com/JuliaBinaryWrappers/GLPK_jll.jl/releases/download/GLPK-v5.0.1+1/GLPK.v5.0.1.x86_64-w64-mingw32.tar.gz"
