[[GLPK]]
arch = "aarch64"
git-tree-sha1 = "3101dc5c239df82734e30f77b30fe31c5e1e528c"
os = "macos"

    [[GLPK.download]]
    sha256 = "f147b6fdaa1ad904e11dfbcf95eeed33ee4159434714c5558be9cf534348f7d8"
    url = "https://github.com/JuliaBinaryWrappers/GLPK_jll.jl/releases/download/GLPK-v5.0.1+0/GLPK.v5.0.1.aarch64-apple-darwin.tar.gz"
[[GLPK]]
arch = "aarch64"
git-tree-sha1 = "b35c5f8d5dc4cc4aeff7fe9a48eaa2927ae6611b"
libc = "glibc"
os = "linux"

    [[GLPK.download]]
    sha256 = "fe57bdaeadfbabacf80e54c7a822a488144cfd1cd9e7a2ed4ceb3ad1a6886aa8"
    url = "https://github.com/JuliaBinaryWrappers/GLPK_jll.jl/releases/download/GLPK-v5.0.1+0/GLPK.v5.0.1.aarch64-linux-gnu.tar.gz"
[[GLPK]]
arch = "aarch64"
git-tree-sha1 = "9c1f6cff93bfab7891ab25c987b39111ad5ab0c3"
libc = "musl"
os = "linux"

    [[GLPK.download]]
    sha256 = "5339c80d5b9fcb6bcef81b97b8013d882cd7b2b41ff9fd65b92f865ac5ebe0d8"
    url = "https://github.com/JuliaBinaryWrappers/GLPK_jll.jl/releases/download/GLPK-v5.0.1+0/GLPK.v5.0.1.aarch64-linux-musl.tar.gz"
[[GLPK]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4a333649cff610c70dc6238a83067dfb4423a37b"
libc = "glibc"
os = "linux"

    [[GLPK.download]]
    sha256 = "e04c394c802d5962fc0536d46f1f3a4744dcbdf7751cb7dffca86f5187f2e636"
    url = "https://github.com/JuliaBinaryWrappers/GLPK_jll.jl/releases/download/GLPK-v5.0.1+0/GLPK.v5.0.1.armv6l-linux-gnueabihf.tar.gz"
[[GLPK]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "385c3522310fd22818a2dd7e482908857a33eb50"
libc = "musl"
os = "linux"

    [[GLPK.download]]
    sha256 = "c1df233004fa52b780eacfda4b9676637363d15933b3a4124f54bd9ff69f0bf5"
    url = "https://github.com/JuliaBinaryWrappers/GLPK_jll.jl/releases/download/GLPK-v5.0.1+0/GLPK.v5.0.1.armv6l-linux-musleabihf.tar.gz"
[[GLPK]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "98c6519edf50a37ba8c53c6000d7084e5871e644"
libc = "glibc"
os = "linux"

    [[GLPK.download]]
    sha256 = "8927f967ddd5643ed25271648ff6d212dae4ebd6bc7a8ace6b6907ca5e271944"
    url = "https://github.com/JuliaBinaryWrappers/GLPK_jll.jl/releases/download/GLPK-v5.0.1+0/GLPK.v5.0.1.armv7l-linux-gnueabihf.tar.gz"
[[GLPK]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d0b4c1a5459b7f79c128c72ce30c5b7a78b9a4b6"
libc = "musl"
os = "linux"

    [[GLPK.download]]
    sha256 = "e7beeb2b7d2bad9816468e1e19b590356e8ef7666b7d694e166a0bcf586c754e"
    url = "https://github.com/JuliaBinaryWrappers/GLPK_jll.jl/releases/download/GLPK-v5.0.1+0/GLPK.v5.0.1.armv7l-linux-musleabihf.tar.gz"
[[GLPK]]
arch = "i686"
git-tree-sha1 = "02a366221ed957be5af249ebd4cbecdcb7cca43e"
libc = "glibc"
os = "linux"

    [[GLPK.download]]
    sha256 = "ca51f86bc40856bea85c3fe5384656e54396f838beb07bfba22eb4bd7da0c88f"
    url = "https://github.com/JuliaBinaryWrappers/GLPK_jll.jl/releases/download/GLPK-v5.0.1+0/GLPK.v5.0.1.i686-linux-gnu.tar.gz"
[[GLPK]]
arch = "i686"
git-tree-sha1 = "b23b564f647864f3849915d94cb59c1369e4f6a8"
libc = "musl"
os = "linux"

    [[GLPK.download]]
    sha256 = "66eea7bafe78afb5ced25be09050ca185e8ed3c9d8174eee6c1d8c17856e569a"
    url = "https://github.com/JuliaBinaryWrappers/GLPK_jll.jl/releases/download/GLPK-v5.0.1+0/GLPK.v5.0.1.i686-linux-musl.tar.gz"
[[GLPK]]
arch = "i686"
git-tree-sha1 = "a2aa68050f8b2725c5e87302852d75445dd7e851"
os = "windows"

    [[GLPK.download]]
    sha256 = "7cdd4030d222913c998e39d13d5bbf51ec964cb8551174662ed38d2a5722309f"
    url = "https://github.com/JuliaBinaryWrappers/GLPK_jll.jl/releases/download/GLPK-v5.0.1+0/GLPK.v5.0.1.i686-w64-mingw32.tar.gz"
[[GLPK]]
arch = "powerpc64le"
git-tree-sha1 = "65a0984160704466953ff6d5cd4062d72f0b0225"
libc = "glibc"
os = "linux"

    [[GLPK.download]]
    sha256 = "10ebfd758acd069d7f080794ebde16ee4c27c4e20120b0c4f1ab116bfeae957d"
    url = "https://github.com/JuliaBinaryWrappers/GLPK_jll.jl/releases/download/GLPK-v5.0.1+0/GLPK.v5.0.1.powerpc64le-linux-gnu.tar.gz"
[[GLPK]]
arch = "x86_64"
git-tree-sha1 = "a8f69d41bc1a2b8d010db7eba6e1e89c06f026b9"
os = "macos"

    [[GLPK.download]]
    sha256 = "11f8cebbbfdcc9c65d24539ff9c73f5dde00eab279152e2a2ebfff5683307189"
    url = "https://github.com/JuliaBinaryWrappers/GLPK_jll.jl/releases/download/GLPK-v5.0.1+0/GLPK.v5.0.1.x86_64-apple-darwin.tar.gz"
[[GLPK]]
arch = "x86_64"
git-tree-sha1 = "85106650a8d6ac252610dd8412d610fc614f96b7"
libc = "glibc"
os = "linux"

    [[GLPK.download]]
    sha256 = "2ddd491ed10202a1282b3792e8969320598ab43a7a5be4529cba42306dc2cd71"
    url = "https://github.com/JuliaBinaryWrappers/GLPK_jll.jl/releases/download/GLPK-v5.0.1+0/GLPK.v5.0.1.x86_64-linux-gnu.tar.gz"
[[GLPK]]
arch = "x86_64"
git-tree-sha1 = "36d9b70f34f87561449bbcf76c5b7291b5e807e0"
libc = "musl"
os = "linux"

    [[GLPK.download]]
    sha256 = "78b5d7191014a13788b2a821b7c8e84cb023e2a90857f408490247b0a7305885"
    url = "https://github.com/JuliaBinaryWrappers/GLPK_jll.jl/releases/download/GLPK-v5.0.1+0/GLPK.v5.0.1.x86_64-linux-musl.tar.gz"
[[GLPK]]
arch = "x86_64"
git-tree-sha1 = "dd79539e012a4849f8fb950e91db35d75a51acb2"
os = "freebsd"

    [[GLPK.download]]
    sha256 = "8197e5c780031fc96c2c58284439ee8ae85172c0c0ae12d4fc16a094ae927bdd"
    url = "https://github.com/JuliaBinaryWrappers/GLPK_jll.jl/releases/download/GLPK-v5.0.1+0/GLPK.v5.0.1.x86_64-unknown-freebsd.tar.gz"
[[GLPK]]
arch = "x86_64"
git-tree-sha1 = "045139e18384db7ad3054f8620be0848a26e813d"
os = "windows"

    [[GLPK.download]]
    sha256 = "e852d92c7efe1da17f0b382c43ada645ab435135c4afeb98e4852a2877798217"
    url = "https://github.com/JuliaBinaryWrappers/GLPK_jll.jl/releases/download/GLPK-v5.0.1+0/GLPK.v5.0.1.x86_64-w64-mingw32.tar.gz"
