[[GLPK]]
arch = "aarch64"
git-tree-sha1 = "0180cd19d94b3b81811b9f74e93a360a8bb0667f"
libc = "musl"
os = "linux"

    [[GLPK.download]]
    sha256 = "7b9b11348ab06085e137eeed6956f1ee01e3a396f2ee36953eed469814310d0f"
    url = "https://github.com/JuliaBinaryWrappers/GLPK_jll.jl/releases/download/GLPK-v4.64.0+0/GLPK.v4.64.0.aarch64-linux-musl.tar.gz"
[[GLPK]]
arch = "i686"
git-tree-sha1 = "639ed1064c4012ab42dd0886aabdf3bf08d36465"
os = "windows"

    [[GLPK.download]]
    sha256 = "93f7f3dfb879104d1bc432f26bb95e4c4e8b0899e9efc10d2ac07ee056e6de69"
    url = "https://github.com/JuliaBinaryWrappers/GLPK_jll.jl/releases/download/GLPK-v4.64.0+0/GLPK.v4.64.0.i686-w64-mingw32.tar.gz"
[[GLPK]]
arch = "x86_64"
git-tree-sha1 = "215b56a1c10b40cba01b88031107baf7100d4758"
libc = "musl"
os = "linux"

    [[GLPK.download]]
    sha256 = "fe6be21fe113704ad4a4ac74dc030f57d32595277ed5a019fe09290891846e68"
    url = "https://github.com/JuliaBinaryWrappers/GLPK_jll.jl/releases/download/GLPK-v4.64.0+0/GLPK.v4.64.0.x86_64-linux-musl.tar.gz"
[[GLPK]]
arch = "i686"
git-tree-sha1 = "ebef94a64289c83df902211caa57c21c7121c48a"
libc = "glibc"
os = "linux"

    [[GLPK.download]]
    sha256 = "117d1e82ff562fd23f3db2d317f8fcbcb9950cb8845d9115b4138950a0e6d217"
    url = "https://github.com/JuliaBinaryWrappers/GLPK_jll.jl/releases/download/GLPK-v4.64.0+0/GLPK.v4.64.0.i686-linux-gnu.tar.gz"
[[GLPK]]
arch = "armv7l"
git-tree-sha1 = "57cc7f4dab34f632bb122bbf4ce659150744953b"
libc = "glibc"
os = "linux"

    [[GLPK.download]]
    sha256 = "c7cd3c2863da37b440246e4c1a64095308790873126f13de7e0c5f348c96c51c"
    url = "https://github.com/JuliaBinaryWrappers/GLPK_jll.jl/releases/download/GLPK-v4.64.0+0/GLPK.v4.64.0.armv7l-linux-gnueabihf.tar.gz"
[[GLPK]]
arch = "aarch64"
git-tree-sha1 = "375431dd5e1e4fce5aa5f2ca571c508194755cda"
libc = "glibc"
os = "linux"

    [[GLPK.download]]
    sha256 = "5fd8dbb8793f4169a1dfe61e84382dfcc9c7c472f9a67bccf619612ac8eb9bde"
    url = "https://github.com/JuliaBinaryWrappers/GLPK_jll.jl/releases/download/GLPK-v4.64.0+0/GLPK.v4.64.0.aarch64-linux-gnu.tar.gz"
[[GLPK]]
arch = "x86_64"
git-tree-sha1 = "858b2d052d839c235b149aa393239b2ed50d0039"
libc = "glibc"
os = "linux"

    [[GLPK.download]]
    sha256 = "272fc8d812f4ca1023b77af6a85b02a89695cc6daf14318eba41b456de2eb746"
    url = "https://github.com/JuliaBinaryWrappers/GLPK_jll.jl/releases/download/GLPK-v4.64.0+0/GLPK.v4.64.0.x86_64-linux-gnu.tar.gz"
[[GLPK]]
arch = "powerpc64le"
git-tree-sha1 = "11b9d8c214e87e7f8e76521adddf4493ddfb1b57"
libc = "glibc"
os = "linux"

    [[GLPK.download]]
    sha256 = "7e70cfcab425e0c84f9e38b0f3dfbeb522ee73c809a2050efd3b838e18a00cac"
    url = "https://github.com/JuliaBinaryWrappers/GLPK_jll.jl/releases/download/GLPK-v4.64.0+0/GLPK.v4.64.0.powerpc64le-linux-gnu.tar.gz"
[[GLPK]]
arch = "x86_64"
git-tree-sha1 = "af440916ec156d5a2e1b46aeaa6e836ce5cbf41c"
os = "macos"

    [[GLPK.download]]
    sha256 = "1ac7e16a51bfc377687ecdf935b6b6d8f7c067186b6a8a80e1da0aff7c7acabc"
    url = "https://github.com/JuliaBinaryWrappers/GLPK_jll.jl/releases/download/GLPK-v4.64.0+0/GLPK.v4.64.0.x86_64-apple-darwin14.tar.gz"
[[GLPK]]
arch = "x86_64"
git-tree-sha1 = "debd0fbf94eff454d2f3e97be6bb91501991e933"
os = "freebsd"

    [[GLPK.download]]
    sha256 = "0f4f2204d4789bbbbb8349429114d86eee27d3df7b6d3312292159771d99e5a6"
    url = "https://github.com/JuliaBinaryWrappers/GLPK_jll.jl/releases/download/GLPK-v4.64.0+0/GLPK.v4.64.0.x86_64-unknown-freebsd11.1.tar.gz"
[[GLPK]]
arch = "i686"
git-tree-sha1 = "00323a152d17b10fae61e44b0a3860496e2dc1c4"
libc = "musl"
os = "linux"

    [[GLPK.download]]
    sha256 = "50f2385c68998941ea885c407d397bba3f3893cee108f8f2c99e78570e2a7731"
    url = "https://github.com/JuliaBinaryWrappers/GLPK_jll.jl/releases/download/GLPK-v4.64.0+0/GLPK.v4.64.0.i686-linux-musl.tar.gz"
[[GLPK]]
arch = "armv7l"
git-tree-sha1 = "77e0e29139a7b5c4576d90230db2b4468cfaca61"
libc = "musl"
os = "linux"

    [[GLPK.download]]
    sha256 = "5c339702a738896f6e0a8526f0b6837fce2c1f7fb26a7416a34f7b0b6e20056e"
    url = "https://github.com/JuliaBinaryWrappers/GLPK_jll.jl/releases/download/GLPK-v4.64.0+0/GLPK.v4.64.0.armv7l-linux-musleabihf.tar.gz"
[[GLPK]]
arch = "x86_64"
git-tree-sha1 = "890e2dad03c362550aac0533efba0e9f2977ae49"
os = "windows"

    [[GLPK.download]]
    sha256 = "99baca281baf7c8f9e55a6686f98e3d12575d9a760494d19556b22ece9cc109b"
    url = "https://github.com/JuliaBinaryWrappers/GLPK_jll.jl/releases/download/GLPK-v4.64.0+0/GLPK.v4.64.0.x86_64-w64-mingw32.tar.gz"
