[[GLPK]]
arch = "aarch64"
git-tree-sha1 = "cbf680f5235e56721e91fc85f93f120a1d52460c"
libc = "glibc"
os = "linux"

    [[GLPK.download]]
    sha256 = "aff39b73cb5a167ee7fae045612fdf87b3be5271524db361f20f0ee7a13932f4"
    url = "https://github.com/JuliaBinaryWrappers/GLPK_jll.jl/releases/download/GLPK-v5.0.0+0/GLPK.v5.0.0.aarch64-linux-gnu.tar.gz"
[[GLPK]]
arch = "aarch64"
git-tree-sha1 = "edf63bb48392391fe88d17f0807f47ef72fe5566"
libc = "musl"
os = "linux"

    [[GLPK.download]]
    sha256 = "0fdb5fc8a691af85a1f3dbe29b2b67e9b72dc1ea8835b1a6a68c9517ebbf3028"
    url = "https://github.com/JuliaBinaryWrappers/GLPK_jll.jl/releases/download/GLPK-v5.0.0+0/GLPK.v5.0.0.aarch64-linux-musl.tar.gz"
[[GLPK]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0f4b9f020f71e8dc84be452b3b897e655af2a411"
libc = "glibc"
os = "linux"

    [[GLPK.download]]
    sha256 = "d6be7ae5ffbc7317d986642ae3b79056579eec4c3b93c5c0d83a7f5671f21eb6"
    url = "https://github.com/JuliaBinaryWrappers/GLPK_jll.jl/releases/download/GLPK-v5.0.0+0/GLPK.v5.0.0.armv7l-linux-gnueabihf.tar.gz"
[[GLPK]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "523dd01349465a39d04aea8d4b612b42eeb62154"
libc = "musl"
os = "linux"

    [[GLPK.download]]
    sha256 = "ffff1c7568e9e723f4d05b257aa1869467e314a11c2f7eba81d8155087f4e2b2"
    url = "https://github.com/JuliaBinaryWrappers/GLPK_jll.jl/releases/download/GLPK-v5.0.0+0/GLPK.v5.0.0.armv7l-linux-musleabihf.tar.gz"
[[GLPK]]
arch = "i686"
git-tree-sha1 = "75ffd16cf9c29cdef3264cb0161d5b38161c3dbe"
libc = "glibc"
os = "linux"

    [[GLPK.download]]
    sha256 = "9c4142ca8fa9405ab34fe6831258b05cca9ff59cbb4c28fb88287961f91cdc98"
    url = "https://github.com/JuliaBinaryWrappers/GLPK_jll.jl/releases/download/GLPK-v5.0.0+0/GLPK.v5.0.0.i686-linux-gnu.tar.gz"
[[GLPK]]
arch = "i686"
git-tree-sha1 = "96f095c95dd0f008f93b91d46a582b3972ae5372"
libc = "musl"
os = "linux"

    [[GLPK.download]]
    sha256 = "1744eae6aec4c596833fd9379d76a94d957c440c8e0b5cad4bfbd6c08c61678a"
    url = "https://github.com/JuliaBinaryWrappers/GLPK_jll.jl/releases/download/GLPK-v5.0.0+0/GLPK.v5.0.0.i686-linux-musl.tar.gz"
[[GLPK]]
arch = "i686"
git-tree-sha1 = "630a76d5866d82ff3e1c34ed2b2a33d050ced19c"
os = "windows"

    [[GLPK.download]]
    sha256 = "b31ffb40c448fee73eccd14a5fa72002aaf2e77b63601c302339eb4481344998"
    url = "https://github.com/JuliaBinaryWrappers/GLPK_jll.jl/releases/download/GLPK-v5.0.0+0/GLPK.v5.0.0.i686-w64-mingw32.tar.gz"
[[GLPK]]
arch = "powerpc64le"
git-tree-sha1 = "a53e8d6be241ec307003822fb6bd9c0e34761795"
libc = "glibc"
os = "linux"

    [[GLPK.download]]
    sha256 = "9105b674554ef2128eeb39080be071f32d4c532a5dc88bc82c3c120a901cccf8"
    url = "https://github.com/JuliaBinaryWrappers/GLPK_jll.jl/releases/download/GLPK-v5.0.0+0/GLPK.v5.0.0.powerpc64le-linux-gnu.tar.gz"
[[GLPK]]
arch = "x86_64"
git-tree-sha1 = "32adbb04b3f6c30d78386bd8631fdec954c03760"
os = "macos"

    [[GLPK.download]]
    sha256 = "86124da752680f0f17a2d9d9b85741f05392e9f1ef76dec7c5f3e8c3c3bb6533"
    url = "https://github.com/JuliaBinaryWrappers/GLPK_jll.jl/releases/download/GLPK-v5.0.0+0/GLPK.v5.0.0.x86_64-apple-darwin.tar.gz"
[[GLPK]]
arch = "x86_64"
git-tree-sha1 = "a5520079ce3a2b9db60bef1a461338cb14ccbaac"
libc = "glibc"
os = "linux"

    [[GLPK.download]]
    sha256 = "90984ed1fbf2e53db129f2fa8783d6118fc51833f8a0ef832c1510a09dd93fe3"
    url = "https://github.com/JuliaBinaryWrappers/GLPK_jll.jl/releases/download/GLPK-v5.0.0+0/GLPK.v5.0.0.x86_64-linux-gnu.tar.gz"
[[GLPK]]
arch = "x86_64"
git-tree-sha1 = "9add6dd8f896501ef1bec26a6812beddeb74978a"
libc = "musl"
os = "linux"

    [[GLPK.download]]
    sha256 = "7986fd737a590a55a17235f8d049bb4d28c07dae38bb99dbec4761699e0b27ad"
    url = "https://github.com/JuliaBinaryWrappers/GLPK_jll.jl/releases/download/GLPK-v5.0.0+0/GLPK.v5.0.0.x86_64-linux-musl.tar.gz"
[[GLPK]]
arch = "x86_64"
git-tree-sha1 = "c81bf978016c6be4d8c1da19180b672d1b409b95"
os = "freebsd"

    [[GLPK.download]]
    sha256 = "ef40d0b414b47c34174571c5aa36d50c81b0bb1076df6cf71aa5ada70878afad"
    url = "https://github.com/JuliaBinaryWrappers/GLPK_jll.jl/releases/download/GLPK-v5.0.0+0/GLPK.v5.0.0.x86_64-unknown-freebsd.tar.gz"
[[GLPK]]
arch = "x86_64"
git-tree-sha1 = "ee7fedebbe5675b0b5ab2c29a81b768cd2590598"
os = "windows"

    [[GLPK.download]]
    sha256 = "f30b2f7a0f663848553c2a5fd35bcaa943e6ef3c1e5d58e7689cacb4cd8434b4"
    url = "https://github.com/JuliaBinaryWrappers/GLPK_jll.jl/releases/download/GLPK-v5.0.0+0/GLPK.v5.0.0.x86_64-w64-mingw32.tar.gz"
